name: CI
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15
          - os: macos-15-intel
            cflags: "-mno-sse4.1"
          - os: macos-15-intel
            cflags: "-msse4.1"
          - os: ubuntu-26.04
            cflags: "-mno-sse4.1"
          - os: ubuntu-26.04
            cflags: "-msse4.1"
          - os: ubuntu-26.04-arm
          - os: windows-2025
          - os: windows-11-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
      - run: python -m pip install meson ninja
      - run: meson setup builddir --buildtype=release
        env:
          CFLAGS: ${{ matrix.cflags }}
      - run: meson compile -C _build
      - run: meson test -C _build
