name: CI
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: "1.2.3"
          ninja-version: "1.11.1"
